name: pokedex
description: "Pokedex Flutter app."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  hive: ^2.2.3
  http: ^1.2.1
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
dev_dependencies:
  flutter_lints: ^3.0.0
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/